name: fingerprint_faceid_auth_api
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  aqueduct: ^4.0.0-b1
  mongo_dart: ^0.4.0
  get_it: ^4.0.4
  injectable: ^1.0.4
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0+1

dev_dependencies:
  freezed: ^0.11.5
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1
  build_runner: ^1.10.1
  injectable_generator: ^1.0.4

